--- #YAML:1.0
name:                Log-Facile
version:             0.01
abstract:            Perl extension for facile logging
license:             perl
author:              
    - Kazuhiro Sera <webmaster@seratch.ath.cx>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Class::Accessor::Fast:         0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
