--- #YAML:1.0
name:                Log-Facile
version:             0.03
abstract:            Perl extension for facile logging
license:             perl
author:              
    - Kazuhiro Sera <webmaster@seratch.net>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
